POST http://localhost:8080/signup
Content-Type: application/json

{
    "email": "ibrahim4grace2@gmail.com",
    "password": "123456"
}

###
POST http://localhost:8080/events
Content-Type: application/json

{
    "Name": "test event",
    "Description": "a second test event",
        "Location": "agege test event",
        "DateTime": "2025-01-01T15:30:00.000Z"
}



