POST http://localhost:8080/signup
Content-Type: application/json

{
    "email": "test2@gmail.com",
    "password": "123456"
}

###
POST http://localhost:8080/events
Content-Type: application/json
 Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3QyQGdtYWlsLmNvbSIsImV4cCI6MTczNTMyNDU4NCwidXNlcklkIjoyfQ.f4eejXrxEwynxLzGtNQG7dDMK2y0aswopxvUx-y-IkI

{
    "Name": "3st test event",
    "Description": "test event",
        "Location": "agege test event",
        "DateTime": "2025-01-01T15:30:00.000Z"
}



