POST http://localhost:8080/events/1/register
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3QyQGdtYWlsLmNvbSIsImV4cCI6MTczNTMyMzY5NCwidXNlcklkIjoyfQ.vgGK22vQH4sGyTR2AwDG26KRRpmJuuYTm6sTt3hFMrk