PUT http://localhost:8080/events/1
Content-Type: application/json

{
    "Name": "test event",
    "Description": "A go test event",
        "Location": "agege test event",
        "DateTime": "2025-01-01T15:30:00.000Z"
}